### ISSUE TITLE
calibrate.py Main_Recipe fails

### ISSUE THREAD

**Issue by SeveMonahan** [joshgabriel/MPInterfaces#11]
Here is the stack trace:

`INFO:__main__:setting INCAR parameter SIGMA = 0.025
INFO:__main__:setting INCAR parameter SIGMA = 0.5
INFO:__main__:setting jobs in the directory: Slab__SIGMA__0_025
INFO:__main__:setting INCAR parameter SIGMA = 0.025
INFO:__main__:setting jobs in the directory: Slab__SIGMA__0_025__POTCAR__Pt
INFO:__main__:setting jobs in the directory: Slab__SIGMA__0_025__POTCAR__Pt__IBRION__1
INFO:__main__:setting INCAR parameter IBRION = 1
INFO:__main__:setting jobs in the directory: Slab__SIGMA__0_025__POTCAR__Pt__IBRION__1__KPTS__20
INFO:__main__:setting jobs in the directory: Slab__SIGMA__0_025__POTCAR__Pt__IBRION__1__KPTS__20__ENCUT__400
INFO:__main__:setting INCAR parameter ENCUT = 400
INFO:__main__:setting jobs in the directory: Slab__SIGMA__0_025__POTCAR__Pt__IBRION__1__KPTS__20__ENCUT__400__POS__Pt_155_VAC10THICK11
Traceback (most recent call last):
  File "calibrate.py", line 1178, in <module>
    cal.setup()
  File "calibrate.py", line 237, in setup
    self.setup_matrix_job()
  File "calibrate.py", line 286, in setup_matrix_job
    self.recursive_jobs(n_items, keys, 0)
  File "calibrate.py", line 323, in recursive_jobs
    self.recursive_jobs(n, keys, i + 1)
  File "calibrate.py", line 323, in recursive_jobs
    self.recursive_jobs(n, keys, i + 1)
  File "calibrate.py", line 323, in recursive_jobs
    self.recursive_jobs(n, keys, i + 1)
  [Previous line repeated 1 more times]
  File "calibrate.py", line 314, in recursive_jobs
    self.add_job(name=job_dir, job_dir=self.job_dir)
  File "calibrate.py", line 803, in add_job
    reuse_path=self.reuse_paths)
  File "/home/covington/Documents/MPInterfaces_Feb_13/MPInterfaces/mpinterfaces/instrument.py", line 53, in __init__
    self.incar = Incar.from_dict(incar.as_dict())
AttributeError: can't set attribute
`

Josh Gabriel says he has seen this before.

**Comment by SeveMonahan** [comment]
OK I have a good lead on what's causing this.

The __init__ which is throwing the AttributeError is for  MPINTVaspInputSet in instrument.py. Looking through the pymatgen code, I found this ( pymatgen/pymatgen/io/vasp/sets.py [grep for "DictSet"]) :
"
            Note that in the **new scheme**,
            ediff_per_atom and hubbard_u are no longer args. Instead, the
            config_dict supports EDIFF_PER_ATOM and EDIFF keys. The former
            scales with # of atoms, the latter does not. If both are
            present, EDIFF is preferred. To force such settings, just supply
            user_incar_settings={"EDIFF": 1e-5, "LDAU": False} for example.
"
which implies an API change is to blame.

Also the original "self.incar = ..." error can be fixed by adding 'incar = "aaa"   ' to the top of class (I don't think the value matters, its just about initializing the value.) If you fix similar errors for poscar, potcar, and kpoints, eventually you get this error:
"
File "/home/covington/Documents/MPInterfaces_Feb_13/MPInterfaces/mpinterfaces/instrument.py", line 85, in __init__
    ediff_per_atom=False, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ediff_per_atom'
"
Which is one of the things mentioned in the "new scheme" comment.

So this implies the API at the boundary needs to be reworked somehow.

**Comment by joshgabriel** [comment]
Good catch and analysis .. can you specify which pymatgen version this is ?

**Comment by SeveMonahan** [comment]
This is on the master version of MPInterfaces (so pymatgen 4.6)

**Comment by joshgabriel** [comment]
some possibly useful reference info on this issue: from http://stackoverflow.com/questions/27396339/attributeerror-cant-set-attribute
""
when the attribute you're attempting to change is actually a property that doesn't have a setter. If you have access to the library' s code, adding a setter would solve the problem.
""

**Comment by joshgabriel** [comment]
Fixed the issue by a few variable name changes refer commits [https://github.com/joshgabriel/MPInterfaces/commit/7117724ee5db0296cd9ace24edf6c63d84af59ff](url)

pymatgen has declared the names incar, kpoints, poscar, potcar as properties under pymatgen.io.vasp.sets.py
